module quantized_sram #(
    parameter ADDR_WIDTH = 10,
    parameter DATA_WIDTH = 8,
    parameter MEM_FILE = ""  // Path to .mem hex file (from export_weights_mem.py)
)(
    input wire clk,
    input wire [ADDR_WIDTH-1:0] addr,
    input wire re, // Read enable (Triggered by Spike_In)
    output reg signed [DATA_WIDTH-1:0] data_out
);
    // Standard SRAM memory array holding INT8 Quantized weights
    reg signed [DATA_WIDTH-1:0] mem [0:(1<<ADDR_WIDTH)-1];
    
    // Load trained weights from .mem file at simulation start
    // These files are generated by export_weights_mem.py from the PyTorch model
    initial begin
        if (MEM_FILE != "") begin
            $readmemh(MEM_FILE, mem);
            $display("[SRAM] Loaded weights from %s", MEM_FILE);
        end
    end

    always @(posedge clk) begin
        // POWER SAVING: Read Enable is uniquely tied to incoming Spikes!
        // If re == 0, the SRAM matrix is not activated, saving dynamic memory power
        if (re) begin
            data_out <= mem[addr];
        end else begin
            // Latched value or zero to prevent MAC accumulation propagation
            data_out <= {DATA_WIDTH{1'b0}}; 
        end
    end
endmodule
