import argparse
import re
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


"""
Visualize preprocessed training dataset and derive conclusions in one file.

Expected input format:
- Directory containing .npz files generated by preprocess_dataset.py
- Each .npz has:
  - x: [T, 2, H, W] (channel 0=OFF, channel 1=ON)
  - y: scalar label (0..9)

Key updates for real preprocessed data:
- Streaming stats (does not load all samples into memory).
- Representative subset support via --sample-mode stratified/random/sequential.
"""


LABEL_REGEX = re.compile(r"_label(\d)_")


def infer_label_from_filename(path: Path):
    m = LABEL_REGEX.search(path.name)
    if m is None:
        return None
    return int(m.group(1))


def list_npz_files(data_dir: Path):
    files = sorted(data_dir.glob("*.npz"))
    if not files:
        raise FileNotFoundError(f"No .npz files found in {data_dir}")
    return files


def select_files(files, max_samples=0, sample_mode="stratified", seed=0):
    if max_samples <= 0 or max_samples >= len(files):
        return files

    rng = np.random.default_rng(seed)

    if sample_mode == "sequential":
        return files[:max_samples]

    if sample_mode == "random":
        idx = rng.choice(len(files), size=max_samples, replace=False)
        return [files[i] for i in sorted(idx)]

    # stratified: try to keep class coverage balanced
    by_class = {k: [] for k in range(10)}
    unknown = []
    for fp in files:
        k = infer_label_from_filename(fp)
        if k is None:
            unknown.append(fp)
        else:
            by_class[k].append(fp)

    if unknown:
        # Fallback to random if class cannot be inferred from filename.
        idx = rng.choice(len(files), size=max_samples, replace=False)
        return [files[i] for i in sorted(idx)]

    for k in range(10):
        rng.shuffle(by_class[k])

    base = max_samples // 10
    rem = max_samples % 10
    selected = []

    for k in range(10):
        take = min(base, len(by_class[k]))
        selected.extend(by_class[k][:take])
        by_class[k] = by_class[k][take:]

    # Distribute remainder and any shortfall round-robin.
    cls_order = list(range(10))
    rng.shuffle(cls_order)
    while len(selected) < max_samples:
        progressed = False
        for k in cls_order:
            if by_class[k]:
                selected.append(by_class[k].pop())
                progressed = True
                if len(selected) == max_samples:
                    break
        if not progressed:
            break

    return sorted(selected)


def derive_conclusions(stats):
    conclusions = []
    present = stats["class_counts"] > 0
    present_counts = stats["class_counts"][present]

    if present_counts.size < 10:
        conclusions.append(
            f"Only {present_counts.size}/10 classes are present in this analyzed subset; "
            "class-level conclusions may be partial."
        )

    if present_counts.size > 1:
        min_c = present_counts.min()
        max_c = present_counts.max()
        ratio = max_c / max(min_c, 1)
        if ratio < 1.2:
            conclusions.append("Class distribution is well balanced across present digits.")
        elif ratio < 2.0:
            conclusions.append("Class distribution is moderately imbalanced; mild reweighting may help.")
        else:
            conclusions.append("Class distribution is strongly imbalanced; use class weighting or sampling.")
    else:
        conclusions.append("Class distribution is single-class; this subset is not suitable for classifier evaluation.")

    sparsity_mean = stats["sparsity_mean"]
    if sparsity_mean > 0.97:
        conclusions.append("Data is highly sparse (>97% zeros), which is favorable for event-driven SNNs.")
    elif sparsity_mean > 0.90:
        conclusions.append("Data is sparse (>90% zeros), suitable for sparse/event computation.")
    else:
        conclusions.append("Data is relatively dense; consider stronger denoising or clipping.")

    on_ratio = stats["on_ratio"]
    if 0.45 <= on_ratio <= 0.55:
        conclusions.append("ON/OFF activity is balanced, indicating stable polarity representation.")
    elif on_ratio > 0.55:
        conclusions.append("ON events dominate; review sensor bias or normalization if this is unexpected.")
    else:
        conclusions.append("OFF events dominate; review sensor bias or normalization if this is unexpected.")

    peak_bin = int(np.argmax(stats["temporal_mean"]))
    conclusions.append(f"Temporal activity peaks around bin {peak_bin} (0-based).")

    class_energy = stats["class_energy"]
    present_energy_idx = np.where(stats["class_counts"] > 0)[0]
    if len(present_energy_idx) >= 2:
        strongest = int(present_energy_idx[np.argmax(class_energy[present_energy_idx])])
        weakest = int(present_energy_idx[np.argmin(class_energy[present_energy_idx])])
        conclusions.append(
            f"Average activity differs by class (strongest present class: {strongest}, weakest: {weakest})."
        )

    return conclusions


def main():
    parser = argparse.ArgumentParser(description="Visualize preprocessed training dataset and print conclusions.")
    parser.add_argument("--data-dir", type=Path, default=Path("preprocessed_train"), help="Directory with .npz files")
    parser.add_argument("--max-samples", type=int, default=0, help="Analyze first/selected N samples (0 = all)")
    parser.add_argument(
        "--sample-mode",
        type=str,
        choices=["stratified", "random", "sequential"],
        default="stratified",
        help="Subset selection mode when --max-samples > 0",
    )
    parser.add_argument("--seed", type=int, default=0, help="Random seed for subset selection")
    parser.add_argument("--save-fig", type=Path, default=None, help="Optional path to save figure (e.g., report.png)")
    args = parser.parse_args()

    files = list_npz_files(args.data_dir)
    selected = select_files(files, max_samples=args.max_samples, sample_mode=args.sample_mode, seed=args.seed)

    first = np.load(selected[0])
    x0 = first["x"].astype(np.float32)
    y0 = int(first["y"])
    if x0.ndim != 4:
        raise ValueError(f"Expected x shape [T,2,H,W], got {x0.shape}")
    t, c, h, w = x0.shape
    if c != 2:
        raise ValueError(f"Expected channel dimension 2 (OFF/ON), got {c}")

    class_counts = np.zeros(10, dtype=np.int64)
    temporal_sum = np.zeros(t, dtype=np.float64)
    off_map_sum = np.zeros((h, w), dtype=np.float64)
    on_map_sum = np.zeros((h, w), dtype=np.float64)
    class_event_sum = np.zeros(10, dtype=np.float64)
    class_sample_count = np.zeros(10, dtype=np.int64)
    sparsity_values = []

    off_total = 0.0
    on_total = 0.0

    def update_from_sample(x, y):
        nonlocal off_total, on_total
        class_counts[y] += 1
        class_sample_count[y] += 1

        temporal_sum[:] += x.sum(axis=(1, 2, 3))
        off_map_sum[:, :] += x[:, 0, :, :].sum(axis=0)
        on_map_sum[:, :] += x[:, 1, :, :].sum(axis=0)

        off = float(x[:, 0, :, :].sum())
        on = float(x[:, 1, :, :].sum())
        off_total += off
        on_total += on
        class_event_sum[y] += off + on

        nonzero = np.count_nonzero(x)
        total = np.prod(x.shape)
        sparsity_values.append(1.0 - (nonzero / max(total, 1)))

    update_from_sample(x0, y0)
    for fp in selected[1:]:
        d = np.load(fp)
        x = d["x"].astype(np.float32)
        y = int(d["y"])
        if x.shape != (t, c, h, w):
            raise ValueError(f"Inconsistent tensor shape in {fp.name}: {x.shape} != {(t, c, h, w)}")
        update_from_sample(x, y)

    n = len(selected)
    temporal_mean = temporal_sum / max(n, 1)
    off_map = off_map_sum / max(n, 1)
    on_map = on_map_sum / max(n, 1)
    total_events = off_total + on_total
    on_ratio = on_total / total_events if total_events > 0 else 0.0
    sparsity = np.array(sparsity_values, dtype=np.float64)
    sparsity_mean = float(sparsity.mean()) if len(sparsity) else 0.0

    class_energy = np.zeros(10, dtype=np.float64)
    valid_cls = class_sample_count > 0
    class_energy[valid_cls] = class_event_sum[valid_cls] / class_sample_count[valid_cls]

    stats = {
        "class_counts": class_counts,
        "temporal_mean": temporal_mean,
        "on_ratio": on_ratio,
        "sparsity_mean": sparsity_mean,
        "class_energy": class_energy,
    }
    conclusions = derive_conclusions(stats)

    print("=== Preprocessed Training Dataset Summary ===")
    print(f"Total files found: {len(files)}")
    print(f"Files analyzed: {n} (sample mode: {args.sample_mode})")
    print(f"Tensor shape per sample: [T={t}, C={c}, H={h}, W={w}]")
    print(f"Class counts in analyzed set: {class_counts.tolist()}")
    print(f"Total OFF events: {off_total:.2f}")
    print(f"Total ON events:  {on_total:.2f}")
    print(f"ON ratio: {on_ratio:.4f}")
    print(f"Mean sparsity: {sparsity_mean:.4f}")
    print("")
    print("=== Conclusions ===")
    for i, line in enumerate(conclusions, start=1):
        print(f"{i}. {line}")

    fig, axes = plt.subplots(2, 3, figsize=(16, 9))
    ax = axes.ravel()

    ax[0].bar(np.arange(10), class_counts, color="steelblue")
    ax[0].set_title("Class Distribution")
    ax[0].set_xlabel("Digit")
    ax[0].set_ylabel("Count")
    ax[0].set_xticks(np.arange(10))

    ax[1].plot(np.arange(t), temporal_mean, marker="o", color="darkorange")
    ax[1].set_title("Temporal Activity (Mean per Sample)")
    ax[1].set_xlabel("Time Bin")
    ax[1].set_ylabel("Event Count")

    ax[2].bar(["OFF", "ON"], [off_total, on_total], color=["firebrick", "royalblue"])
    ax[2].set_title("Polarity Activity")
    ax[2].set_ylabel("Total Event Count")

    im_off = ax[3].imshow(off_map, cmap="Reds")
    ax[3].set_title("Mean OFF Spatial Map")
    ax[3].set_xlabel("X")
    ax[3].set_ylabel("Y")
    fig.colorbar(im_off, ax=ax[3], fraction=0.046, pad=0.04)

    im_on = ax[4].imshow(on_map, cmap="Blues")
    ax[4].set_title("Mean ON Spatial Map")
    ax[4].set_xlabel("X")
    ax[4].set_ylabel("Y")
    fig.colorbar(im_on, ax=ax[4], fraction=0.046, pad=0.04)

    ax[5].hist(sparsity, bins=20, color="seagreen", edgecolor="black", alpha=0.8)
    ax[5].set_title("Sample Sparsity Distribution")
    ax[5].set_xlabel("Sparsity (fraction of zeros)")
    ax[5].set_ylabel("Samples")

    fig.suptitle("Preprocessed Training Dataset Analysis", fontsize=14)
    fig.tight_layout()

    if args.save_fig is not None:
        args.save_fig.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(args.save_fig, dpi=150, bbox_inches="tight")
        print(f"\nSaved figure: {args.save_fig}")

    plt.show()


if __name__ == "__main__":
    main()

